### ISSUE TITLE
Create a demo project

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/django-suit-dashboard#32]
A demo project with working examples could help to see how things work and what we can do with this app.

**Comment by mark5280** [comment]
Thanks for considering this.  It would be great to have a working example and be able to experiment with it to see how everything is configured, works together, etc.  Thank you!

**Comment by vipinmca0714** [comment]
Hi Pawamoy,

Any update on above demo project...please share..

**Comment by Pawamoy** [comment]
Hi @vipinmca0714 , sorry I'm busy these days, I'll try to find some time this week end.

**Comment by Pawamoy** [comment]
Hey !

Check the demo here: https://github.com/Pawamoy/suit-dashboard-demo

It's not much but I hope it will be improved later.
