### ISSUE TITLE
How to set charts to auto-refresh data..

### ISSUE THREAD

**Issue by vipinmca0714** [Pawamoy/django-suit-dashboard#36]
Hello Pawamoy,

In your previous documentation, i have seen this in your example. now its replaced by new documentation i think. Please help me in, how to make highchart auto refresh data.

Regards
Vipin

**Comment by Pawamoy** [comment]
Yup, documentation and API have changed.

You have an example here is the docs: http://django-suit-dashboard.readthedocs.io/en/latest/usage.html#real-time-highcharts-widget, and the section about real-time widgets: http://django-suit-dashboard.readthedocs.io/en/latest/usage.html#real-time-widgets.

Basically, you need 3 things:

1. a widget with a ``get_updated_content(self)`` method (you need to subclass ``Widget``)
2. wrap it in the ``realtime`` function (imported from ``suit_dashboard.widgets`` or just ``suit_dashboard``) **where it is executed at startup**
3. add the real-time URLs into your admin site ``get_urls`` method with something like ``custom_urls += get_realtime_urls(self.admin_view)``
4. (optionnal) specify url name, regex and time interval: this can be done by adding these attributes to your widget subclass, or by passing them as parameters to the realtime function.

The HTML/Javascript code to update the widget (linked to it through its ``template`` attribute, please see the docs) is left to you, but here is a good starting point:

```
{% load static %}

{% if widget.name %}<h2>{{ widget.name }}</h2>{% endif %}

<div id="{{ widget.html_id }}"></div>

{% with chart_url='admin:'|add:widget.url_name %}
  <script>
    // get initial content
    var dataset = {{ widget.content|safe }};
    // draw a highcharts chart or do something else with your widget's content
    var chart = $('#{{ widget.html_id }}').highcharts(dataset);

    $(function () {
      setInterval(function() {
        // get the updated content
        $.getJSON("{% url chart_url %}", function(refreshed_data) {
          // select your chart object
          var chart = $('#{{ widget.html_id }}').highcharts();
          // do something with it, here we add the data as a point to our dataset
          chart.series[0].addPoint(refreshed_data, false);
          chart.redraw();
        });
      }, {{ widget.time_interval }});
    });
  </script>
{% endwith %}
```

I you have something more specific in mind, please let me know.

By the way, I'm planning to add a demo project, you will hear from me when it's ready :)

**Comment by vipinmca0714** [comment]
Thank you Pawamoy....waiting for that demo project...please share the update when it is ready. :)

Regards
Vipin

**Comment by vipinmca0714** [comment]
Hi Pawamoy, One more thing, can you share the previous demo project which was on previous version. 

Actually i am using the older version as of now. will try to upgrade to new one when u share the demo for  latest version.

Regards
Vipin

**Comment by Pawamoy** [comment]
Actually there wasn't any demo project for the previous versions. If you speak about the docs, then you can build them locally for the desired version by cloning the repo and run `tox -e docs`. The output will be in `dist/docs`, just open `index.html`. You will need to install `tox` with `pip install tox`.

If the current documentation lacks things or is unclear, please let me know in separate issues!

**Comment by vipinmca0714** [comment]
Thanks.. :)
