### ISSUE TITLE
Use with django-constance

### ISSUE THREAD

**Issue by arybin93** [pawamoy/django-suit-dashboard#63]
If you use [django-constance](https://github.com/jazzband/django-constance):

In my admin file I added:
`from constance.admin import ConstanceAdmin, Config`
`admin.site.register([Config], ConstanceAdmin)`

How do you think, is it need to add to note about it in docs?

**Comment by pawamoy** [comment]
I'm not sure to understand: how is it related to django-suit-dashboard? Your two lines of code are pieces of the usual `admin.py`, which has nothing to do with django-suit-dashboard.

Did something not work with this app before you add these two lines?

**Comment by arybin93** [comment]
I try to use django-suit-dashboard in my project. In my project I also use django-constance.  
And after this row:
`admin.site = DashboardSite()` 
`admin.sites.site = admin.site` 
`admin.autodiscover()`

Django-constance in admin panel link broken with 404 error.
I added the code presented in the topic of the issue and fix the error.

**Comment by pawamoy** [comment]
Ah, I get it now. Out of curiosity: can I see your `INSTALLED_APPS`?

**Comment by pawamoy** [comment]
Yes, I thought about the order. Thank you for trying it out. Until we find a way to automatically fix this, we can for sure add a note in the documentation. I'll do it later, unless you want to send a PR :slightly_smiling_face:.
